server:
  port: 8082

  spring:
    datasource:
      url: jdbc:postgresql://localhost:5432/microservices
      username: postgres
      password: vilish123
jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
